### ISSUE TITLE
大佬，你这个库有oc版的没

### ISSUE THREAD

**Issue by yang-haofeng** [gltwy/LTScrollView#1]
暂时没提供，你可以尝试桥接解决

**Comment by gltwy** [comment]
暂时没提供，你可以尝试桥接解决

**Comment by storm52** [comment]
OC的可以看看我这个https://github.com/storm52/LWXDetailController

**Comment by hsuyelin** [comment]
发现一处bug：
快速滑到切页，标题颜色要等到滑动结束后才显示颜色，中途经过的标题都不会显示颜色；

想提二处改进:
当标题超过一定数量后，不能够自动的向后滑动，就是适应；
缺少一个滚动过程中的方法

**Comment by storm52** [comment]
颜色配置可以看tabpage的设置

**Comment by storm52** [comment]
颜色和滑动过程都可以tabbar配置

**Comment by gltwy** [comment]
@hsuyelin 有空了改进一下哈
@storm52 嗯嗯

**Comment by yang-haofeng** [comment]
谢谢
