### ISSUE TITLE
LTAdvancedManager 调用 scrollToIndex(index: Int)无效

### ISSUE THREAD

**Issue by WuFuPeiQian** [gltwy/LTScrollView#106]
将“ pageView.scrollToIndex(index: index)” 修改为“titleView.scrollToIndex(index: index)”有效

**Comment by TomeLuo** [comment]
LTPageView文件下115行注释掉就可以
//        guard !layout.isSinglePageView else { return }
用的地方，加个延时
  DispatchQueue.main.asyncAfter(deadline: .now()+0.1) { [unowned self] in
            self.advancedManager.scrollToIndex(index: self.selectedIndex)
        }

**Comment by gltwy** [comment]
@TomeLuo @WuFuPeiQian 已修复～ 请更新到最新版本

**Comment by WuFuPeiQian** [comment]
验证成功
