### ISSUE TITLE
我是自定义导航栏的，现在出现下面的问题，能否帮我解决下

### ISSUE THREAD

**Issue by NOMBER2011** [gltwy/LTScrollView#11]
1.刚进入这个界面出现
![wechatimg363](https://user-images.githubusercontent.com/13688441/40298009-2eefc5b6-5d14-11e8-9dbb-5c0aaa2ced43.jpeg)

2.向上滑动出现
![wechatimg365](https://user-images.githubusercontent.com/13688441/40298028-3f0e6010-5d14-11e8-9658-7831c286a08e.jpeg)

**Comment by gltwy** [comment]
尝试一下以下方法，具体产生原因得看一下怎么实现的
if (version == iOS11) {
        tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
    }else {
        self.automaticallyAdjustsScrollViewInsets = NO;
    }
