### ISSUE TITLE
glt_scrollView = tableView无效果

### ISSUE THREAD

**Issue by SunshineBrother** [gltwy/LTScrollView#117]
我想要在func glt_scrollViewDidScroll(_ scrollView: UIScrollView) 代理中监控滚动距离，按照文档在子controller里面设置glt_scrollView = tableView，但是glt_scrollViewDidScroll代理并不能监控滚动距离。现在项目LTSimple案例也能够复现

**Comment by gltwy** [comment]
@SunshineBrother 未复现。
