### ISSUE TITLE
滑块底部线是否可以开放更多属性

### ISSUE THREAD

**Issue by wlingf** [gltwy/LTScrollView#12]
滑块底部线一般都是直角的，但是我的项目需求是圆角的，没有相应的api更改滑块底部线的属性

**Comment by wlingf** [comment]
当点击标题的时候  滑块底部线滑动的不够自然  没有滑动的感觉 像是显隐的感觉 可以优化下

**Comment by gltwy** [comment]
@wlingf 增加了bottomLineCornerRadius属性可以设置圆角，增加了isClickScrollAnimation属性，可以设置动画的开启和关闭，默认关闭

**Comment by wlingf** [comment]
好的  我更新下

**Comment by wlingf** [comment]
isClickScrollAnimation = yes 点击的时候怎么标题放大了   isNeedScale = no 这个设置不是放大标题的嘛

**Comment by gltwy** [comment]
@wlingf 已修复 - 0.1.7
