### ISSUE TITLE
点击标题是否可以增加滑动动画

### ISSUE THREAD

**Issue by hsuyelin** [gltwy/LTScrollView#13]
就是现在点击标题的话太生硬了，是否能够点击标题，指示器滑动有动画

**Comment by gltwy** [comment]
@hsuyelin 增加了isClickScrollAnimation属性，可以设置动画的开启和关闭，默认关闭

**Comment by hsuyelin** [comment]
更新效率真的高，目前遇到的最好用的了，赞一个 ~
