### ISSUE TITLE
Xcode9.4 报错"Unsupported Swift Version"

### ISSUE THREAD

**Issue by RichardDuan** [gltwy/LTScrollView#14]
The target “LTScrollView” contains source code developed with Swift 2.x. Xcode 9 does not support building or migrating Swift 2.x targets.

Use Xcode 8.x to migrate the code to Swift 3.
我的Xcode的是9.4版本。

**Comment by gltwy** [comment]
@RichardDuan Xcode中设置一下Swift Language Version，4.0以及以上都可以
