### ISSUE TITLE
是否可以在标题上加入消息数？

### ISSUE THREAD

**Issue by threeQuestion** [gltwy/LTScrollView#15]
大神，我需要在标题上右上角加入圆形的消息数，怎么弄？

**Comment by gltwy** [comment]
@threeQuestion 可以自定义的，没在框架内部加，如有需要，可以私聊我

**Comment by threeQuestion** [comment]
大神，怎么做，我可以随意修改title区域




| |
薛鹏
邮箱：pengbaby1993@163.com
|

签名由 网易邮箱大师 定制

在2018年06月30日 22:41，GaoLiuTong 写道：

@threeQuestion 可以自定义的，没在框架内部加，如有需要，可以私聊我
