### ISSUE TITLE
出现多个警告

### ISSUE THREAD

**Issue by jdleung** [gltwy/LTScrollView#18]
pod 安装成功

但仍出现多个警告：
Use of undeclared type 'LTLayout'
Use of undeclared type 'LTAdvancedManager'
Use of undeclared type 'LTAdvancedScrollViewDelegate'

Pods
- Pods
-- LTScrollView
上面文件夹里面也有这些定义的，但仍有警告

**Comment by gltwy** [comment]
@jdleung Xcode中设置一下Swift Language Version，4.0以及以上都可以
