### ISSUE TITLE
子VC reloadRowsAtIndexPaths 的时候向上滑

### ISSUE THREAD

**Issue by tom1230123** [gltwy/LTScrollView#20]
在子VC中，reload某一行会向上跳动下，这样测试在点击第一行会向上滑。
![qq20180620-155513](https://user-images.githubusercontent.com/13695425/41645042-610f8540-74a2-11e8-8e63-cca532ff3562.png)
如果用reloadData基本所以都会向上滑

**Comment by gltwy** [comment]
@tom1230123 这个暂时没发现，刚更新了0.1.7版本，您可以再看一下，如果还有问题，随时联系

**Comment by hydyy** [comment]
我子 control ，tableView 动态高， reloadData 之后位置错乱的严重

**Comment by hydyy** [comment]
刚测试了一下，动高 cell 会跳，固定高没事

**Comment by gltwy** [comment]
@hydyy 我这边没能复现出来，方便具体描述一下吗？我QQ:1282990794
