### ISSUE TITLE
点击或滑动的时候

### ISSUE THREAD

**Issue by XiaoYiS** [gltwy/LTScrollView#21]
我在点击和滑动的时候希望要保持原来的y偏移位置不变，我需要怎么修改呢，现在是我每次点击和滑动都会将我的y的偏移量设置为头部view的高

**Comment by gltwy** [comment]
@XiaoYiS 没太明白，具体描述一下吧

**Comment by XiaoYiS** [comment]
就是点击对应的按钮会滑动到对应的scrollview下面，但是偏移量会重置（比如我在第一个tab的时候上滑动了，此时点击第二个tab，他会自动下滑到默认的偏移高度位置），我希望是点击对应的Tab按钮渲染其他的控制器（scrollview）的时候，主视图的偏移量会默认保留上一次的滑动，而不是每一次点击都会偏移到最开始设置的顶部高度

**Comment by XiaoYiS** [comment]
@gltwy ,有空麻烦回答一下呗
