### ISSUE TITLE
怎么做到每次点击title滑块的时候，都刷新对应的控制器数据

### ISSUE THREAD

**Issue by SunsgneDZ** [gltwy/LTScrollView#24]
你好，怎么做到每次点击title滑块的时候，都刷新对应的控制器数据，我发现对应的控制器视图viewWillAppear:(BOOL)animated这个方法都只执行了一次，有什么方法能够点击就能够走对应控制器里的方法（通知除外）

**Comment by gltwy** [comment]
在manager中可以监听到点击事件，然后你利用通知、属性、代理、block都是可以的。自己尝试吧！
