### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by JQHee** [gltwy/LTScrollView#25]
如果自控制器的tableView 有sectionheaderview，会卡在页面中间

**Comment by gltwy** [comment]
卡在中间是你的tableView的设置样式问题吧，style 是 plain还是group呢？具体描述一下你的问题吧

**Comment by JQHee** [comment]
<img width="325" alt="image" src="https://user-images.githubusercontent.com/12505317/42407667-1a8b3d9a-81f3-11e8-970b-2f969ea65b02.png">

我只是在你的demo中给plain样式的tableview添加sectionheaderView

**Comment by gltwy** [comment]
@JQHee 把plain改成group就好了
