### ISSUE TITLE
关于下拉刷新有些界面显示不全，结合DZNEmptyDataSet使用问题。

### ISSUE THREAD

**Issue by Ting-coder** [gltwy/LTScrollView#26]
我按照你的方式添加的MJ的刷新控件，为什么有些界面自动调用下拉刷新的时候会缩进去一部分，然后搭配DZNEmptyDataSet使用的时候会强制把我的collectionView撑到和屏幕一样大是为什么？

**Comment by Ting-coder** [comment]
我看了你实现的层级，DZNEmptyDataSet的问题是因为它显示的大小是根据CollectionView的大小来衡量的，而你用的是ScrollView的Offset来实现的，所以会出现撑开的问题，因为DZNEmptyDataSet的视图是和ScrollView的大小相同的，你的实现能改成下面的CollectionView的高度和下面可以滚动视图区域的高度相同呢？而不是使用contentInset的方式，不然DZNEmptyDataSet是无法使用的。。。。。。

**Comment by gltwy** [comment]
@Ting-coder 这个是需要修改整个实现逻辑的，DZNEmptyDataSet是展示没有内容的时候，给一个占位的吧，建议自己实现一下吧🙂

**Comment by Ting-coder** [comment]
好的好的，我再试试，感谢你的回答。
