### ISSUE TITLE
0.1.7版本 《下拉放大-导航渐变》 在iPhone X上面tableview最后一行显示不出来

### ISSUE THREAD

**Issue by Jamesltesim** [gltwy/LTScrollView#27]
作者您好，您的demo非常好，已经Star。

但是在使用过程中遇到一个UI适配的问题，在 0.1.7版本 第三个案例《下拉放大-导航渐变》 在iPhone X上面tableview最后一行显示不出来。能否在您方便的时候更新一下？

期待您的回复

**Comment by Jamesltesim** [comment]
其他案例，使用过程中没有遇到这种问题

**Comment by gltwy** [comment]
@Jamesltesim 我在Demo中没有发现你说的tableview最后一行显示不出来那种现象，能具体描述一下怎么复现的吗？
