### ISSUE TITLE
样式上的一些问题

### ISSUE THREAD

**Issue by KnightWL** [gltwy/LTScrollView#29]
作者大大您好！非常感激您写出这套LTScrollView帮我解决了多个scrollView嵌套的老大难问题！我目前在使用0.1.8版本的时候出现了一点小问题：
1、页面底部左右滑动时会出现horizontalIndicator；
2、页面底部有一个整个容器cell的分割线（距screen.left 15px）。
查询您的源码发现分别是这两个view导致的：
1、LTSimpleManager的tableView的separatorStyle并没有设置成.none；
2、LTPageView的scrollView的showHorizontalIndicator属性并没有设置成false。
但是我翻阅您的源码并没有找到能够不污染源码来设置这两个属性的方式，希望得到您的指引告诉我如果不污染源码的前提下来设置成我想要的样式，或者如果没有的话希望您在下一版本的迭代中可以考虑这个问题，谢谢！~

**Comment by gltwy** [comment]
@KnightWL 感谢支持，0.1.9中已修改，可更新
