### ISSUE TITLE
怎么取消simplemanager分栏吸顶效果

### ISSUE THREAD

**Issue by yhvh009** [gltwy/LTScrollView#30]
尝试设置simplemanager的hoverY属性，但是还是有一点小问题，当滚动到分栏垂直位置一半的时候松手，view会自动滚下来把分栏露出来，必须把分栏全部滑出去页面才不会自动滚动。

**Comment by gltwy** [comment]
@yhvh009 这个没太明白，具体描述一下

**Comment by yhvh009** [comment]
就是当分栏滑动到页面顶部一半位置的时候松手，分栏会自动下滑把完整的分栏漏出来，而不会停留在只漏出来一半的位置
