### ISSUE TITLE
增加tableview的头视图后偏移量不对，会往上偏移

### ISSUE THREAD

**Issue by zxCindy** [gltwy/LTScrollView#36]
您好，进阶版-刷新控件在中间这个类型，给tableview的头视图后，第一个title对应的页面偏移量有问题，但是其他title对应的没问题，能指点一下是什么原因造成的么，谢谢

**Comment by gltwy** [comment]
@zxCindy 暂时的解决方案，利用DispatchQueue.main.after函数延时0.001秒后加

**Comment by gltwy** [comment]
@zxCindy 嗯，这个如果在设置特别大字体的时候，确实会出现这种问题，尝试过修改字体，但是会存在一些小问题，我近期修复吧，感谢支持
