### ISSUE TITLE
如果LTAdvancedTestOneVC不止有上面tableView，在tableView的正上方还有一个View，位置应该如何处理

### ISSUE THREAD

**Issue by a1259667899** [gltwy/LTScrollView#4]
如果LTAdvancedTestOneVC不止有上面tableView，在tableView的正上方还有一个View，位置应该如何处理，直接在LTAdvancedTestOneVC.view上添加一个view，会显示不出来

**Comment by gltwy** [comment]
@a1259667899 
可以尝试把view放到section中，如有疑问，随时沟通。
