### ISSUE TITLE
如果headerView想要实现改变高度的效果，应该做？

### ISSUE THREAD

**Issue by a1259667899** [gltwy/LTScrollView#42]

**Comment by gltwy** [comment]
@a1259667899 

/* 动态改变header的高度 */
@objc public var glt_headerHeight: CGFloat = 0.0

**Comment by a1259667899** [comment]
进阶版本的还存在一个问题，就是子控制器的tableView如果有sectionHeader，这个sectionHader的位置是异常的

**Comment by yuehongjie** [comment]
进阶版，我是下面这么做的，对我是有效的，不保证对各位大佬有用.....

// 改变 headerView 的高度 -- add by yue （不保证完全正确）

`func updateHeaderHeight(height:Float){

        //新老高度
        let newHeight = CGFloat(height)
        let oldHeight = kHeaderHeight
        
        print("newHeight:\(newHeight)   oldHeight:\(oldHeight)  lastDiffTitleToNav: \(lastDiffTitleToNav)")
        //标题栏（tab 标签）的位置需要计算
        var Y: CGFloat = 0
        
        if newHeight < oldHeight {
            // lastDiffTitleToNav 应该是 tab 栏到顶部的位置
            if lastDiffTitleToNav <= hoverY {
                //如果新的高度比老的高度小，即高度变矮了，且当前 tab 栏，已经在悬停的位置，则保持其在悬停位置不变
                Y = hoverY
            }else {
                //如果高度变矮了，且当前 tab 栏还没有悬停，则 tab 栏应该相应的向上移动高度差，
                //注意：移动后，如果 Y 小于了悬停位置，应该修正位置，让其停留在悬停位置（修正代码在下面）
                Y = lastDiffTitleToNav - (oldHeight - newHeight)
            }
        }else {
            if lastDiffTitleToNav <= hoverY {
                //如果新的高度比老的高度大，即高度变高了，如果此时 tab 栏已在悬停位置，则应该下沉（移）高度差
                Y = newHeight - oldHeight
            }else {
                //如果高度变高了，且当前 tab 栏还没有悬停，则 tab 也应该下沉高度差位移
                Y = lastDiffTitleToNav + (newHeight - oldHeight)
            }
        }
        
        //修正悬停的位置
        if Y < hoverY {
            Y = hoverY
        }
        //修正 tab 栏到顶部的位置
        lastDiffTitleToNav = Y
        print("Y:\(Y)")
        
        //设置新的高度，改变头部高度
        kHeaderHeight = newHeight
        var newFrame = self.headerView?.frame
        newFrame?.size.height = kHeaderHeight
        self.headerView?.frame = newFrame!
        //设置 tab 栏的位置
        titleView.frame.origin.y = Y

        //计算当前页面是否需要回滚
        self.setupContentSizeBoundsHeightAdjust()
        //header 改变高度后，每一个控制器的内容都滚动到相应的位置
        for viewController in viewControllers {
            self.contentScrollViewScrollConfig(viewController)
            scrollInsets(viewController, kHeaderHeight+layout.sliderHeight)
        }
       
    }`

**Comment by looha518** [comment]
> 进阶版，我是下面这么做的，对我是有效的，不保证对各位大佬有用.....
> 
> ```swift
> // 在 LTAdvancedManager 源码中增加，改变 headerView 的高度 -- add by yue （不保证完全正确）
> func updateHeaderHeight(height:Float){
> 
>         //新老高度
>         let newHeight = CGFloat(height)
>         let oldHeight = kHeaderHeight
>         //高度不变，不刷新
>         if newHeight == oldHeight {
>             print("高度未发生变化")
>             return
>         }
> 
>         print("newHeight:\(newHeight)   oldHeight:\(oldHeight)  lastDiffTitleToNav: \(lastDiffTitleToNav)")
>         //标题栏（tab 标签）的位置需要计算
>         var Y: CGFloat = 0
>         
>         if newHeight < oldHeight {
>             // lastDiffTitleToNav 应该是 tab 栏到顶部的位置
>             if lastDiffTitleToNav <= hoverY {
>                 //如果新的高度比老的高度小，即高度变矮了，且当前 tab 栏，已经在悬停的位置，则保持其在悬停位置不变
>                 Y = hoverY
>             }else {
>                 //如果高度变矮了，且当前 tab 栏还没有悬停，则 tab 栏应该相应的向上移动高度差，
>                 //注意：移动后，如果 Y 小于了悬停位置，应该修正位置，让其停留在悬停位置（修正代码在下面）
>                 Y = lastDiffTitleToNav - (oldHeight - newHeight)
>             }
>         }else {
>             if lastDiffTitleToNav <= hoverY {
>                 //如果新的高度比老的高度大，即高度变高了，如果此时 tab 栏已在悬停位置，则应该下沉（移）高度差
>                 Y = newHeight - oldHeight
>             }else {
>                 //如果高度变高了，且当前 tab 栏还没有悬停，则 tab 也应该下沉高度差位移
>                 Y = lastDiffTitleToNav + (newHeight - oldHeight)
>             }
>         }
>         
>         //修正悬停的位置
>         if Y < hoverY {
>             Y = hoverY
>         }
>         //修正 tab 栏到顶部的位置
>         lastDiffTitleToNav = Y
>         print("Y:\(Y)")
>         
>         //设置新的高度，改变头部高度
>         kHeaderHeight = newHeight
>         var newFrame = self.headerView?.frame
>         newFrame?.size.height = kHeaderHeight
>         self.headerView?.frame = newFrame!
>         //设置 tab 栏的位置
>         titleView.frame.origin.y = Y
> 
>         //计算当前页面是否需要回滚
>         self.setupContentSizeBoundsHeightAdjust()
>         //header 改变高度后，每一个控制器的内容都滚动到相应的位置
>         for viewController in viewControllers {
>             self.contentScrollViewScrollConfig(viewController)
>             scrollInsets(viewController, kHeaderHeight+layout.sliderHeight)
>         }
>        
> }
> ```

有种情况下，比如当向上滑动到第10行的时候（10行以后的能看到），当增加header高度的时候，header的增加的部分会遮住第10行或者更多

**Comment by looha518** [comment]
> @a1259667899
> 
> /* 动态改变header的高度 */
> @objc public var glt_headerHeight: CGFloat = 0.0

大佬，LTAdvancedManager的怎么动态设置高度
