### ISSUE TITLE
能否新增更新数据源来刷新布局的方法

### ISSUE THREAD

**Issue by f2yu** [gltwy/LTScrollView#48]

**Comment by wongzigii** [comment]
+1

**Comment by wongzigii** [comment]
现在太蛋疼了，每次都要重新实例化一个新的对象

**Comment by 530003247** [comment]
> 现在太蛋疼了，每次都要重新实例化一个新的对象

老铁   你是怎么释放原有的  能否看看代码  我这边也重新实例  发现原有的并没有完全释放 cpu爬到90%+

**Comment by lyq226809** [comment]
@gltwy  请问更新数据源怎么使用呢？demo也没相关说明呢....

**Comment by gltwy** [comment]
@lyq226809 参考最新demo
