### ISSUE TITLE
swift4.2又有新语法出来，麻烦您有时间改下

### ISSUE THREAD

**Issue by dashuang1234** [gltwy/LTScrollView#54]
例如：UITableViewStyle->UITableView.Style

**Comment by leospace** [comment]
是的，每次新增一个pod组件就需要修改 LTScrollView 为 swift4.0 才能编译通过，希望尽快修改一下

**Comment by leospace** [comment]
> 是的，每次新增一个pod组件就需要修改 LTScrollView 为 swift4.0 才能编译通过，希望尽快修改一下

不过用这种方式可以暂时解决问题，在podfile中加入以下代码：

# Swift 版本声明
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if ['LTScrollView'].include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
                config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            end
        end
    end
end
