### ISSUE TITLE
子控制器、LTPageView、LTPageTitleView等都不会释放、内存泄露。

### ISSUE THREAD

**Issue by liuzizhong** [gltwy/LTScrollView#58]
只有LTAdvancedManager会释放，其他的均不释放，可以在Demo中测试一下。

**Comment by liuzizhong** [comment]
麻烦作者定位一下哪部分引起的。

**Comment by liuzizhong** [comment]
extension LTAdvancedManager {
    private func deallocConfig() {
        for viewController in viewControllers {
            viewController.glt_scrollView?.delegate = nil
        }
        pageView.removeFromSuperview()
    }
}

这个方法中需要将移除，不移除会内存泄露。

**Comment by liuzizhong** [comment]
extension LTAdvancedManager {
    private func deallocConfig() {
        for viewController in viewControllers {
            viewController.glt_scrollView?.delegate = nil
        }
        titleView.removeFromSuperview()
        pageView.removeFromSuperview()
    }
}
这样才行。

**Comment by gltwy** [comment]
@liuzizhong 感谢指出

**Comment by codejun9527** [comment]
> extension LTAdvancedManager {
> private func deallocConfig() {
> for viewController in viewControllers {
> viewController.glt_scrollView?.delegate = nil
> }
> titleView.removeFromSuperview()
> pageView.removeFromSuperview()
> }
> }
> 这样才行。

back的时候调用吗

**Comment by codejun9527** [comment]
@liuzizhong  pageview的子组件也不释放  解决了吗
