### ISSUE TITLE
header高度适配 iPhone XR12.1

### ISSUE THREAD

**Issue by GItHubNanmu77** [gltwy/LTScrollView#60]
![image](https://user-images.githubusercontent.com/22163174/50684097-55d51700-104f-11e9-8fe7-d912b3163ab6.png)
![image](https://user-images.githubusercontent.com/22163174/50684118-608fac00-104f-11e9-85fc-e1c2bd6e1a05.png)
用的模拟器，真机没试过。感谢。

**Comment by gltwy** [comment]
@GItHubNanmu77 这个是外部自己控制的
