### ISSUE TITLE
UICollectionView 的demo没有

### ISSUE THREAD

**Issue by shether** [gltwy/LTScrollView#61]
UICollectionView 的demo没有

**Comment by gltwy** [comment]
@shether 道理一样的，glt_scrollView = collectionview就好了

**Comment by cccchris** [comment]
@gltwy 我错了

**Comment by MayerFeng** [comment]
collectionview 能加mjFooter 么 我的咋不行呢

**Comment by cccchris** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
