### ISSUE TITLE
v0.2.0 没有自定义titleView使用scrollToIndex滚动到指定位置方法无效果,如何解决

### ISSUE THREAD

**Issue by zhengjianliang** [gltwy/LTScrollView#70]

**Comment by sxm5220** [comment]
self.advancedManager.pageView.scrollView.contentOffset = CGPoint.init(x: screenWidth() * selectedSegmentIndex, y: 0) 自己修改源码解决

**Comment by sxm5220** [comment]
UIView.animate(withDuration: 0.5) {
            self.advancedManager.pageView.scrollView.contentOffset.x = screenWidth() * CGFloat(selectedSegmentIndex)
        } 自行修改源码

**Comment by happyhefagui** [comment]
作者您好，因为完全不懂swift，还请问下self.advancedManager.pageView.scrollView.contentOffset.x = screenWidth() * CGFloat(selectedSegmentIndex)是加载那个方法中啊！！！谢谢

**Comment by MataHu** [comment]
请问在哪里加

**Comment by MataHu** [comment]
> } 自行修改源码

请问你加上了吗，在哪加，感谢

**Comment by MataHu** [comment]
> UIView.animate(withDuration: 0.5) {
> self.advancedManager.pageView.scrollView.contentOffset.x = screenWidth() * CGFloat(selectedSegmentIndex)
> } 自行修改源码

请问在哪里加
