### ISSUE TITLE
设置hoverY, 很少数据时，向上滑动，

### ISSUE THREAD

**Issue by shiliujiejie** [gltwy/LTScrollView#74]
demo中 ，设置hoverY后，将数据源条数改为1 - 4 （很少数据， cell顶出titleView 下边范围，  将LTAdvancedManager 文件 第 161行，改为：glt_scrollView.contentSize.height = glt_scrollView.bounds.height - sliderH - hoverY。 在看效果

**Comment by gltwy** [comment]
@shiliujiejie 已修复
