### ISSUE TITLE
tableview下来刷新8plus和iphone x  机型无法正确回弹位置

### ISSUE THREAD

**Issue by MrzYc** [gltwy/LTScrollView#81]
<img width="409" alt="WeChat605e175268e0c846247b786a6e9460ed" src="https://user-images.githubusercontent.com/24274120/63833362-6f8fe980-c9a5-11e9-8877-738635ea9885.png">

**Comment by q1019736727** [comment]
我的也是，8p或则X以后的机型无法回弹
