### ISSUE TITLE
LTScrollExtension.swift中如下代码是什么意思

### ISSUE THREAD

**Issue by bw-bianwei** [gltwy/LTScrollView#93]
```swift
public class func initializeOnce() {
        DispatchQueue.once(token: UIDevice.current.identifierForVendor?.uuidString ?? "LTScrollView") {
            let didScroll = "X25vdGlmeURpZFNjcm9sbA==".glt_base64Decoding()
            let originSelector = Selector((didScroll))
            let swizzleSelector = #selector(glt_scrollViewDidScroll)
            glt_swizzleMethod(self, originSelector, swizzleSelector)
        }
    }
```
这段代码中“ let didScroll = "X25vdGlmeURpZFNjcm9sbA==".glt_base64Decoding()”是什么意思， "X25vdGlmeURpZFNjcm9sbA=="这一串是怎么得到的

**Comment by Bianwei520** [comment]
`public class func initializeOnce() {
        DispatchQueue.once(token: UIDevice.current.identifierForVendor?.uuidString ?? "LTScrollView") {
            let didScroll = "X25vdGlmeURpZFNjcm9sbA==".glt_base64Decoding()
            let originSelector = Selector((didScroll))
            let swizzleSelector = #selector(glt_scrollViewDidScroll)
            glt_swizzleMethod(self, originSelector, swizzleSelector)
        }
    }`

**Comment by championfu** [comment]
base54解码就是"_notifyDidScroll"，UIKit里的私有方法，怕被拒就做了一下简单的加密
